version: 2
updates:
  - package-ecosystem: npm
    directory: /app
    schedule:
      interval: monthly
    groups:
      npm-minor:
        update-types: [minor, patch]
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: cargo
    directory: /app/src-tauri
    schedule:
      interval: monthly
    groups:
      cargo-minor:
        update-types: [minor, patch]
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
